# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eh-am.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: eduardo aleixo
  avatar: https://avatars0.githubusercontent.com/u/6951209?v=3&s=460
  gravatar: # email md5 hash
  description: personal webpage for brazilian web developer Eduardo Aleixo # used by search engines

  # Header and footer text
  header_text: >

  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>, modified by eduardo aleixo

  # Icons
  rss: false
  email_address: eduardoaleixomartins@gmail.com # full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "eh-am"
  google_plus:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  tumblr:
  twitter: "invalidindex" #"twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-59191973-2 # tracking id, e.g. "UA-000000-01"
  disqus_shortname:

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
#paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
