name: weekly digest

on:
  schedule:
    - cron: 0 */12 * * *
  pull_request:
    branches: [main]


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - run: make digest
        env:
          POCKET_CONSUMER_KEY: '${{ secrets.POCKET_CONSUMER_KEY }}'
          POCKET_ACCESS_TOKEN: '${{ secrets.POCKET_ACCESS_TOKEN }}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[weekly digest] get latest data"

      # Also deploy
      # TODO: unify with gh-pages
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
